// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoLifeBot.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NoLifeBot.Data.Migrations
{
    [DbContext(typeof(NoLifeBotDbContext))]
    [Migration("20210918020659_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NoLifeBot.Data.Entities.VoicePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasDeafened")
                        .HasColumnType("boolean")
                        .HasColumnName("was_deafened");

                    b.Property<bool>("WasMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("was_muted");

                    b.Property<bool>("WasStreaming")
                        .HasColumnType("boolean")
                        .HasColumnName("was_streaming");

                    b.HasKey("Id")
                        .HasName("pk_voice_periods");

                    b.ToTable("voice_periods");
                });
#pragma warning restore 612, 618
        }
    }
}
